In [7]:
import math
import pandas as pd
import numpy as np

In [2]:
# algoritmo 174
def matrizBiOrdinaria(NumColuna, NumLinhas, elemento=0):
    matriz = [[0 for i in range(NumColuna)] for j in range(NumLinhas)]
    for y in range(NumColuna):
        for x in range(NumLinhas):
            matriz[x][y] = elemento
    return matriz

In [3]:
# algoritmo 175
def count1():
    for i in range(101):
        print(i)
count1()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [4]:
# algoritmo 182
def count2():
    for i in range(100,0,-1):
        print(i)
count2()

100
99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1

In [64]:
# algoritmo 182 
def entradaNum1():
    lista = []
    for i in range(11):
        num = input("Digite um numero: ")
        if num != '':
            lista.append(float(num))
    for i in lista:
        print(i/2)


entradaNum1()

17.0
2.5
17.0
11.5
2.5
33.5
22.5
17.0
11.5
32.0
3.5

In [ ]:
# algoritmo 185
def entradaNum2():
    lista = []
    for i in range(16):
        num = float(input("Digite um numero: "))
        lista.append(num)
    for i in lista:
        print(math.sqrt(i))
entradaNum2()

1.7320508075688772
2.23606797749979
18.275666882497067
7.280109889280518
3.4641016151377544
7.280109889280518
6.708203932499369
6.557438524302
2.23606797749979
6.782329983125268
5.830951894845301
5.830951894845301
1.4142135623730951
6.48074069840786
18.520259177452136
1.4142135623730951

In [ ]:
# algoritmo 188
def tabPolForCM():
    table2d = [[i for i in range(5)] for j in range(4)]
    count = 1
    for i in range(4):
        for j in range(5):
            table2d[i][j] = (count * 2.54)
            count += 1
    dfCm = pd.DataFrame(table2d)
    return dfCm

tabela = tabPolForCM()
tabela.head(20)

       0      1      2      3     4
0   2.54   5.08   7.62  10.16  12.7
1  15.24  17.78  20.32  22.86  25.4
2  27.94  30.48  33.02  35.56  38.1
3  40.64  43.18  45.72  48.26  50.8

In [ ]:
# algoritmo 189
def convertCelsius(limitS, limitI, decremento):
    defir = limitS - limitI
    table2d = [[None for _ in range(2)] for _ in range(defir)]
    print(table2d)
    table2d[0][0] = 'Fahrenheit'
    table2d[0][1] = 'Celsius'
    for i in range(1,defir):
        for j in range(0,2):
            table2d[i][1] = limitS
            table2d[i][0] = round(limitS * (9/5) + 32, 2)
            limitS -= decremento
    return table2d
resultado_celsius = convertCelsius(100, 32, 1)
df_temps = pd.DataFrame(resultado_celsius)
df_temps.head(200)

[[None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None]]

             0        1
0   Fahrenheit  Celsius
1        210.2       99
2        206.6       97
3        203.0       95
4        199.4       93
..         ...      ...
63       -13.0      -25
64       -16.6      -27
65       -20.2      -29
66       -23.8      -31
67       -27.4      -33

[68 rows x 2 columns]

In [ ]:
table2d = [[None for _ in range(2)] for _ in range(200)]
table2d = pd.DataFrame(table2d)
table2d.head(200)

        0     1
0    None  None
1    None  None
2    None  None
3    None  None
4    None  None
..    ...   ...
195  None  None
196  None  None
197  None  None
198  None  None
199  None  None

[200 rows x 2 columns]

In [47]:
def create_matrix(colunms, rows):
    """Create a matrix filled with zeros.

    Args:
        colunms (int): The number of columns in the matrix.
        rows (int): The number of rows in the matrix.

    Returns:
        numpy.ndarray: A matrix with the specified number of columns and rows, filled with zeros."""
    return np.zeros((colunms, rows), dtype=object)

testfinal = create_matrix(10, 2)
testfinal = pd.DataFrame(testfinal)
testfinal.head(10)

   0  1
0  0  0
1  0  0
2  0  0
3  0  0
4  0  0
5  0  0
6  0  0
7  0  0
8  0  0
9  0  0

In [23]:
def data_people_matrix():
    """Fill a numpy matrix with input names, age and sex,
    and return data of male people with age 21 or more.

    Returns:
        numpy.ndarray: A numpy matrix with the input data ordered."""
    data = create_matrix(3,20)

    for x in range(20):
        data[x, 0] = input("Digite o nome: ")
        data[x, 1] = int(input("Digite a idade: "))
        data[x, 2] = str(input("Digite o sexo (M para masculino ou F para feminino): "))

    for x in range(20):
        if data[x, 1] > 21 and data[x, 2] == 'M':
            print("\nNome: {}".format(data[x, 0]))

data_people_matrix()

ValueError: invalid literal for int() with base 10: ''

In [25]:
# algoritmo 206
def find_higher_lower(array):
    """"""
    higher = array[0]
    lower = array[0]
    for i in array:
        if i > higher:
            higher = i
        if i < lower:
            lower = i
    
    return higher, lower

def get_array(count_array):
    """"""
    array = np.zeros(count_array)
    for i in range(count_array):
        array[i] = float(input("Digite o número: "))
    
    return array

def len_array():
    """"""
    count_array = int(input("Digite quantos números quer comparar: "))
    return count_array

def algoritmh_higher_lower():
    """"""
    count_array = len_array()
    array = get_array(count_array)
    higher, lower = find_higher_lower(array)
    print("Maior número digitado: {}  Menor número digitado: {}".format(higher, lower))

algoritmh_higher_lower()

Maior número digitado: 78.0  Menor número digitado: 2.0

In [31]:
# algoritmo 209
def ricci_n(n_count):
    A = 1
    B = 2
    C = 3

    print("{}, \n{}, ".format(A, B))

    for _ in range(n_count):
        C = A + B
        print("{}, ".format(C))
        A = C - A
        B = C

def seque_ricci():
    n_count = int(input("Digite n número para n primeiros núemros da sequencia de racci: "))
    ricci_n(n_count)

seque_ricci()

1,
2,
3,
5,
8,
13,
21,
34,
55,
89,
144,
233,
377,
610,
987,
1597,
2584,
4181,
6765,
10946,
17711,
28657,
46368,
75025,
121393,
196418,
317811,
514229,
832040,
1346269,
2178309,
3524578,
5702887,
9227465,

In [33]:
# algoritmo 212
def get_nums():
    array = np.zeros(20)
    for i in range(20):
        array[i] = float(input("Digite o número: "))
    return array

def sum_sqrt(array):
    sum = 0
    for i in array:
        if math.sqrt(i) < 225:
            sum += math.sqrt(i)

    return print("soma: {}".format(sum))

def algo_sum_sqrt():
    array = get_nums()
    sum_sqrt(array)

algo_sum_sqrt()

ValueError: could not convert string to float: ''

In [60]:
# algoritmo 214
def get_grade_frame(lenght):
    grade_frame = create_matrix(3, lenght) 
    for i in range(lenght):
        grade_frame[0, i] = str(input("Digite o nome do aluno: "))
        grade_frame[1, i] = float(input("Digite a nota PR1: "))
        grade_frame[2, i] = float(input("Digite a nota PR2: "))
    
    grade_frame = pd.DataFrame(grade_frame.T, columns=["Nome", "PR1", "PR2"])
    grade_frame.head(lenght)

    return grade_frame

test = get_grade_frame(3)
test.head()

   Nome  PR1  PR2
0  mona  5.0  6.0
1  lola  7.0  8.0
2  joao  7.0  9.0

In [55]:
# algoritmo 217
def get_names(length):
    names_frame = create_matrix(2, length)
    for i in range(length):
        names_frame[0, i] = str(input("Digite o nome: "))
        names_frame[1, i] = len(str(names_frame[0, i]))
    
    names_frame = pd.DataFrame(names_frame.T, columns=["Nome", "Qnt_letras"])
    return names_frame

test_count = get_names(8)
test_count.head(8)

      Nome Tamanho
0   josuke       6
1      dio       3
2   jotaro       6
3   joshph       6
4  giourno       7

In [62]:
# algoritmo 348
def get_grade_frame_upgrade(lenght):
    gradeframe = get_grade_frame(lenght)
    gradeframe["Media"] = (gradeframe["PR1"] + gradeframe["PR2"]) / 2
    return gradeframe

test_grade2 = get_grade_frame_upgrade(5)
test_grade2.head()

     Nome   PR1   PR2 Media
0    mona   5.0   6.0   5.5
1   johan  10.0  10.0  10.0
2  josuke   7.0   8.0   7.5
3  jotaro   7.0   6.0   6.5
4    lola   4.0   7.0   5.5

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=340b9f92-dd81-4b8e-a65c-e3979cb3a8db' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>